#!/usr/bin/env bash

rm -rf dist/*
esbuild src/index.ts --bundle --external:axios --target=chrome60,firefox60,safari12,edge18 \
  --outfile=dist/logger-transport-discord.js --sourcemap --format=iife --global-name=DiscordTransport \
  && esbuild src/index.ts --bundle --external:axios --target=chrome60,firefox60,safari12,edge18 \
  --outfile=dist/logger-transport-discord.min.js --minify --format=iife --global-name=DiscordTransport \
  && tsc -d --emitDeclarationOnly --rootDir src --outDir dist \
  && mv dist/index.d.ts dist/logger-transport-discord.d.ts \
  && refup dist/logger-transport-discord.js DiscordTransport \
  && refup dist/logger-transport-discord.min.js DiscordTransport \
  || exit 1
